// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "llmProvider": string;
      "apiBaseUrl": string;
      "apiKey": string;
      "modelName": string;
      "embeddingEnabled": boolean;
      "embeddingModel": string;
      "language": string;
      "autoIndex": boolean;
      "historyRounds": number;
      "autoHighlight": boolean;
      "colorSummary": string;
      "colorConcept": string;
      "colorArgument": string;
      "colorCharacters": string;
      "colorQuotes": string;
      "colorGuide": string;
    };
  }
}
