name: Release

on:
  push:
    tags:
      - v**

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  create-release:
    uses: zotero-plugin-dev/workflows/.github/workflows/release-plugin.yml@main
    with:
      build: "cd plugin && npm install && npm run build"
      release: "cd plugin && npm run release"
    secrets: inherit
